server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: learn-prometheus
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}